sudo: required
services:
  - docker

before_install:
  - docker build -t hirosan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hirosan/docker-react npm run test
#   - docker run hirosan/docker-react npm run test -- --coverage
